"""empty message

Revision ID: 740e820defb3
Revises: 7799b1e65c21
Create Date: 2017-04-05 09:54:40.844076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740e820defb3'
down_revision = '7799b1e65c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_num')
    # ### end Alembic commands ###
