"""empty message

Revision ID: 879a8537e1e1
Revises: 740e820defb3
Create Date: 2017-07-30 13:10:48.721453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879a8537e1e1'
down_revision = '740e820defb3'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('descript', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    ### end Alembic commands ###
